version: "3"
services:
  matplotlib-seaborn:
    container_name: 'matplotlib-seaborn'
    command: bash -c "jupyter lab --notebook-dir=/home/matplotlib-seaborn --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/home/matplotlib-seaborn
